export const TOGGLE_SIDEBAR = 'admin/TOGGLE_SIDEBAR';
export const TOGGLE_MINIMIZED_SIDEBAR = 'admin/TOGGLE_MINIMIZED_SIDEBAR';
export const ADMIN_SELECT_TEMPLATE_PAGE = 'admin/ADMIN_SELECT_TEMPLATE_PAGE';
